version: '3.5'

services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./workspace:/workspace
    ports:
      - 80:80
      - 443:443

  php:
    image: itxiaoma/php:8.1.0
    #build:
    #  context: ./
    #  dockerfile: Dockerfile_php
    container_name: php
    restart: always
    command: php-fpm
    ports:
      - 9000:9000
    volumes:
      - ./workspace:/workspace
    stdin_open: true
    tty: true

  antd:
    image: bitnami/node:16.17.1
    #build:
    #  context: ./
    #  dockerfile: Dockerfile_antd
    container_name: antd
    ports:
      - 8000:8000
    volumes:
      - ./workspace:/app
    command: tail -f /dev/null
  
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    command:
      --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    privileged: true
    restart: always 
